# Generated by Django 5.0 on 2024-08-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('hide', models.BooleanField(default=False, verbose_name='Hide')),
                ('topping', models.CharField(blank=True, max_length=50, null=True, verbose_name='Topping')),
                ('topping_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Topping Price')),
            ],
        ),
    ]
