# Generated by Django 5.0 on 2024-08-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_fooditem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Sandwich', 'Sandwich'), ('Misal Pav', 'Misal Pav'), ('Dosa', 'Dosa'), ('Pav Bhaji', 'Pav Bhaji'), ('Bhurji', 'Bhurji'), ('Cold Coffee', 'Cold Coffee'), ('Shakes', 'Shakes'), ('Pizza', 'Pizza'), ('Cold Drink', 'Cold Drink'), ('Ice Cream', 'Ice Cream'), ('Mastani', 'Mastani')], max_length=50, verbose_name='Category'),
        ),
    ]
