# Generated by Django 5.0 on 2024-08-16 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_fooditem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('owner', models.CharField(max_length=50, null=True)),
                ('contact', models.IntegerField(null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
            ],
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.CharField(max_length=200, null=True, verbose_name='Description'),
        ),
    ]
