# Generated by Django 5.0 on 2024-08-16 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_branchmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='contact',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10-digit contact number')]),
        ),
    ]
